version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_WS_URL=http://localhost:3001
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - websocket

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge